#file for develop purposes only
version: '2.2'
volumes:
  postgresql_data:
    external: false
  es_data01:
    driver: local

networks:
  salesnet:
    driver: bridge

services:
  db:
    image: postgres:11
    ports:
      - "127.0.0.1:5434:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres-db
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - salesnet
